{% set version = '1.3.14' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsyncrosim
  version: {{ version|replace("-", "_") }}

source:
  url: 
    - https://github.com/syncrosim/rsyncrosim/releases/download/{{ version }}/rsyncrosim_{{ version }}.tar.gz
    - https://github.com/simplejson/simplejson/archive/v{{ version }}.tar.gz
  sha256: efa50fa39db9b0c47eb2cffab0ee758233ef1484ba6f9180e8fe6aa8299d85e6

build:
  merge_build_host: True
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - mkl
    - r-base=4.1.3
    - r-terra=1.5_21
    - r-sf=1.0_7
    - r-pander=0.6.5
    - r-shiny=1.7.2
    - r-tidyr=1.2.0
    - r-presenceabsence=1.1.10
    - r-prroc=1.3.1
    - r-rocr=1.0_11
    - r-ggplot2=3.3.6
    - r-dplyr=1.0.9
    - r-gbm=2.1.8
  run:
    - r-base

test:
  commands:
    - $R -e "library('rsyncrosim')"           # [not win]
    - "\"%R%\" -e \"library('rsyncrosim')\""  # [win]

about:
  home: https://www.apexrms.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: R interface to SyncroSim
  doc_url: https://syncrosim.github.io/rsyncrosim/
  dev_url: https://github.com/syncrosim/rsyncrosim/

extra:
  recipe-maintainers:
    - katieb1